
TODO: bring this up to modern day

THIS IS OLD AND BROKEN

this was originally to aid development/testing on systems without even zlib
(notably the old solaris/sparc setup i had access to, one reason i wanted to
keep external hard dependencies minimal).

zlib was a veeery slow moving target.
But now there is much more activity.
Todays zlib releases have changed meaningfull, even use cmake?

And this here hasn't kept up.

So no, you can not include zlib.

--------- orig ---------

You can directly compile in the zlib into G2CD.

Just drop the zlib source into this directory and then use "make withzlib" or
"make finalwithzlib" in the distribution root directory.

This hopefully gives a little performance gain.

But be WARNED:
* whenever there is a problem with your used zlib version, you have to rebuild
  G2CD this way (you don't have this prob with shared libs, best maintained by
  your OS package system)
* This is just a test, an alpha feature in an alpha software.

This feature may also be handy for people where zlib is not part of the OS
Distribution, but beware of the drawbacks. There will be no new versions or
fixup releases of G2CD when a zlib problem arises to remember you to update.
To stress this out the zlib source is left out of the G2CD distriubution
package.
